name: 'PM2 Deploy Action'
description: 'Run PM2 deploy as a Github Action'
author: 'Felipe Figueroa'
branding:
  icon: 'check-square'
  color: 'orange'
inputs:
  environment:
    description: 'Environment to use'
    default: 'development'
    required: true
  host:
    description: 'remote host'
    default: '127.0.0.1'
    required: false
  path:
    description: 'project path on remote'
    default: '/var/www/project'
    required: false
  repo:
    description: 'https://github.com/matt-ball/newman-action'
    default: 'https://github.com/matt-ball/newman-action'
    required: false
  user:
    description: 'ubuntu'
    default: 'ubuntu'
    required: false
  key:
    description: 'pm2.key'
    default: 'pm2.key'
    required: false
  ref:
    description: 'origin/develop'
    default: 'origin/develop'
    required: false
  configFile:
    description: 'Disable SSL verification and allow self-signed SSL'
    required: false
  postDeploy:
    description: 'Action to run when the deploy finishes. Usually to restart the containers'
    default: 'pm2 ls'
    required: false
  appName:
    description: 'App that should be referenced by its name in the ecosystem.config if any'
    default: 'app'
    required: false
  command:
    description: 'Stop collection run gracefully on error'
    required: false
    default: 'update'
runs:
  using: 'node12'
  main: 'dist/index.js'
